slogan: "liste des fuites trouv√©es"
theme: cerulean
inverse: false
# whether to show h2 and h3 titles in excerpts
show_title_in_excerpt: true
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:
menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
 

links:
  - title: code
    url: https://github.com/alphaleadership/feed/
    intro: "le code ."
    icon: "fa fa-github"
  - title: "My Github"
    url: https://github.com/alphaleadership/
    intro: "My Github account."
    icon: "fa fa-github"


widgets:
- search
- recent_comments

- tagcloud
- recent_posts
- links
- rss  # uncomment this to show an RSS button in the sidebar

rss: atom.xml
fancybox: true
favicon: favicon.png
duoshuo_shortname: #freemindtheme

# Recommended posts
# Dependency: https://github.com/huiwang/hexo-recommended-posts
recommended_posts:
  enabled: false

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: false
jiathis: false

# built-in comment system
#comment_js:
#  type: "github"
 # user: "thomas-iniguez-visioli"
 # repo: "vbcq"
 # client_id: "bf7d4ba11877db88543e"
 # client_secret: "bff8a6b06b745c0bfcdccbe225623ea8e2a057bb"
 # count: 5

# If you want to use gitalk for comments, please uncomment the following, fill in the fields, and comment out the comment_js above.
#comment_gitalk:
#  client_id: "<client_id>"
#  client_secret: "<client_secret>"
#  repo: "<repo-name>"
#  user: "<owner-username>"
